"""empty message

Revision ID: d42b1d960110
Revises: 0ab886ada1ca
Create Date: 2025-04-18 14:23:15.374679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42b1d960110'
down_revision = '0ab886ada1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_pauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_entries_id', sa.UUID(), nullable=False),
    sa.Column('pause_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pause_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['time_entries_id'], ['time_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_pauses')
    op.drop_table('time_entries')
    # ### end Alembic commands ###
