name: Deploy Frontend

on:
    push:
        paths:
            - "frontend/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Sync Frontend to Server
              run: |
                  rsync -avz --delete ./frontend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.PROJECT_PATH }}/frontend

            - name: Build and Deploy on Server
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
                    cd ${{ secrets.PROJECT_PATH }}/frontend

                    npm install
                    npm run build

                    sudo rm -rf /var/www/chronixly.com/html/*
                    sudo cp -r dist/* /var/www/chronixly.com/html/
                  EOF
