name: Deploy Backend

on:
    push:
        paths:
            - "backend/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup SSH Agent
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Sync Frontend to Server
              run: |
                  rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./frontend/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.PROJECT_PATH }}/frontend

            - name: Setup & Restart Backend
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
                    cd ${{ secrets.PROJECT_PATH }}/backend

                    source venv/bin/activate
                    pip install -r requirements.txt
                    flask db upgrade
                    sudo systemctl restart backend
                  EOF
